apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-catalog-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-catalog-api
  template:
    metadata:
      labels:
        app: my-catalog-api
    spec:
      containers:
        - name: my-catalog-api
          image: erhankaraca0/catalogapi
          env:
            - name: TEST_ENV_VAR
              value: "test-env-var"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: s_catalog_api
spec:
  selector:
    app: my-catalog-api
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-catalog-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: s_catalog_api
              servicePort: http